services:
  postgres:
    # PostgreSQL
    image: postgis/postgis:16-3.4
    container_name: sentinel-postgres
    environment:
      POSTGRES_USER: sentinel_admin
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: sentinel_fusion
    ports:
      - "5432:5432"
    volumes:
      - sentinel-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel_admin -d sentinel_fusion"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Message Broker (Kafka in KRaft mode)
  kafka:
    image: apache/kafka:latest
    container_name: sentinel-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Listen on 29092 for internal Docker traffic, 9092 for external Windows traffic
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    volumes:
      - sentinel-kafka-data:/tmp/kraft-combined-logs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 5s
      timeout: 5s
      retries: 10

  sensor-gateway:
    build: ./sensor-gateway
    container_name: sentinel-sensor-gateway
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKERS=kafka:29092 # Points to kafka's internal Docker DNS
    depends_on:
      kafka:
        condition: service_healthy

  fusion-engine:
    build: ./fusion-engine
    container_name: sentinel-fusion-engine
    ports:
      - "8080:8080"
    environment:
      # Hibernate Credentials
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sentinel_fusion
      - SPRING_DATASOURCE_USERNAME=sentinel_admin
      - SPRING_DATASOURCE_PASSWORD=sentinel_password
      # Flyway Credentials
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/sentinel_fusion
      - SPRING_FLYWAY_USER=sentinel_admin
      - SPRING_FLYWAY_PASSWORD=sentinel_password
      # Kafka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  battery-service:
    build: ./battery-service
    container_name: sentinel-battery-service
    ports:
      - "8082:8082"
      - "9090:9090"
    restart: unless-stopped

  interceptor-service:
    build: ./interceptor-service
    container_name: sentinel-interceptor-service
    ports:
      - "8081:8081"
    environment:
      # Connect to Kafka using Docker DNS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      # Connect to the Battery Service using Docker DNS!
      - SPRING_GRPC_CLIENT_CHANNELS_BATTERY_SERVICE_ADDRESS=static://battery-service:9090
    depends_on:
      kafka:
        condition: service_healthy
      battery-service:
        condition: service_started
    restart: on-failure

  dashboard-bff:
    build: ./dashboard-bff
    container_name: sentinel-dashboard-bff
    ports:
      - "3001:3001"
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure

  tactical-dashboard:
    build: ./tactical-dashboard
    container_name: sentinel-tactical-dashboard
    ports:
      - "80:80"
    depends_on:
      - dashboard-bff

  simulation-engine:
    build: ./simulation-engine
    container_name: sentinel-simulation-engine
    ports:
      - "4000:4000"
    environment:
      - GATEWAY_URL=http://sensor-gateway:3000/api/sensors/ping
    depends_on:
      - sensor-gateway

volumes:
  sentinel-db-data:
  sentinel-kafka-data: