server:
  port: 8082 # Standard HTTP port

spring:
  application:
    name: battery-service

  threads:
    virtual:
      enabled: true

  grpc:
    server:
      port: 9090 # Dedicated port for the gRPC binary traffic