server:
  port: 8081

spring:
  application:
    name: interceptor-service

  # Enable Java 21 Virtual Threads for concurrency
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: interceptor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer